language: python

python:
  - "2.7"

sudo: false

services:
  - elasticsearch

addons:
  apt:
    package:
      - nodejs

install:
  # Python test requirements
  - pip install virtualenv virtualenvwrapper
  - pip install autoenv
  - git clone https://github.com/cfpb/sheer
  - pip install -e sheer
  - pip install -r sheer/requirements.txt
  - cp .env_SAMPLE .env
  - sheer index
  - pip install -r test/macro_tests/requirements.txt

  # JavaScript test requirements
  - npm install -g gulp
  - npm install -g bower
  - npm install -g protractor
  - npm install

script:
  # Run tests for JavaScript
  - gulp lint:gulp
  - gulp lint:src
  - gulp test:unit
  - gulp test:coveralls
  - gulp test:macro
  - gulp test:processor
