language: python
sudo: false
dist: trusty

git:
  depth: 10

python:
  - "2.7"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  chrome: stable

cache:
  pip: true

install:
  - ./travis_install.sh

branches:
  only:
    - master

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"

script:
  - ./travis_run.sh

env:
  global:
    - DJANGO_SETTINGS_MODULE=cfgov.settings.test
    - DJANGO_STAGING_HOSTNAME=content.localhost
    - COVERALLS_PARALLEL=true
    - PGPORT=5433

jobs:
  fast_finish: true
  include:
    - stage: Run Tests
      env: RUNTEST=frontend
    - env:
        - RUNTEST=backend
        - TEST_RUNNER=cfgov.test.StdoutCapturingTestRunner
    - stage: Docs Deploy
      if: tag IS present
      env: RUNTEST=docs
      deploy:
        provider: pages
        local_dir: site
        skip-cleanup: true
        github_token: $GITHUB_TOKEN
