language: python

python:
  - "2.7"

sudo: false

services:
  - elasticsearch

addons:
  apt:
    package:
      - nodejs

install:
  # Python test requirements
  - pip install virtualenv virtualenvwrapper
  - pip install autoenv
  - git clone https://github.com/cfpb/sheer
  - pip install -e sheer
  - pip install -r sheer/requirements.txt
  - cp .env_SAMPLE .env
  - sheer index
  - pip install -r _tests/macro_testing/requirements.txt

  # JavaScript test requirements
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g protractor
  - npm install

script:
  # Run tests for JavaScript
  - grunt test

  - cd _tests/macro_testing
  - python test_macros.py
