language: python

python:
  - "2.7"

sudo: false

services:
  - elasticsearch

install:
  # Project configuration requirements.
  - pip install virtualenv virtualenvwrapper
  - pip install autoenv
  - npm install nvm
  - nvm install 4.1.0
  - nvm use 4.1.0
  - npm install -g gulp
  - npm install -g bower

  # Project initialization.
  - python cfgov/manage.py sheer_index
  - chmod +x ./setup.sh
  - ./setup.sh

script:
  - gulp lint
  - gulp test:unit
  - gulp test:coveralls

env:
  - TOXENV=py27
