language: python

python:
  - "2.7"

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - elasticsearch

install:
  # Project configuration requirements.
  - pip install virtualenv virtualenvwrapper
  - pip install autoenv
  # Set g++ version for npm nan.
  # this is terrible
  - find / -name "g++-*"
  - export CXX=g++-4.8
  - $CXX --version
  - npm install nvm
  - nvm install 5.2.0
  - nvm use 5.2.0
  - npm install -g gulp
  - npm install -g bower

  # Project initialization.
  - chmod +x ./setup.sh
  - ./setup.sh test
  - python cfgov/manage.py sheer_index
  - python cfgov/manage.py migrate

script:
  - gulp lint
  - gulp test:unit
  - gulp test:coveralls

env:
    - TOXENV=py27 DJANGO_SETTINGS_MODULE=cfgov.settings.test WORDPRESS=http://www.consumerfinance.gov
