version: "3.3"

services:
    mysql:
        image: vsamov/mysql-5.1.73
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: v1
            MYSQL_USER: v1
            MYSQL_PASSWORD: v1
        volumes:
            - "/var/lib/mysql"
    elasticsearch:
        image: elasticsearch:2.3
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./docker:/apps
        entrypoint: /apps/docker-entrypoint-es-plugins.sh
    python:
        build: .
        ports:
            - "8000:8000"
        environment:
            MYSQL_ROOT_PW: root
            MYSQL_HOST: mysql
            MYSQL_NAME: v1
            MYSQL_USER: v1
            MYSQL_PW: v1
            ES_HOST: elasticsearch
        volumes:
                - ./:/src/cfgov-refresh
                - ./develop-apps:/src/develop-apps
        entrypoint: 
                - sh
                - /src/cfgov-refresh/cfgov/entrypoint.sh
        depends_on:
                - mysql
                - elasticsearch                
        working_dir: /src/cfgov-refresh
        env_file: .env
