site_name: cfgov-refresh
pages:
- Introduction: index.md
- Installation: installation.md
- Building and Deploying for cf.gov: 
    - What's new: whats-new.md
    - New projects: new-projects.md
    - Branching and merging: branching-merging.md
    - Release cadence: release-cadence.md
    - Deployment: deployment.md
    - Feature flags: feature-flags.md
    - Wagtail Pages vs Django views: django-to-wagtail.md
- Front end guidelines:
    - Atomic structure and design: atomic-structure.md
    - Notes on adapting atomic design: notes-on-atomic-design.md
    - Notes on frameworks: notes-on-frameworks.md
theme: readthedocs

markdown_extensions:
    - admonition
    - tables
